# Generated by Django 5.0.1 on 2024-01-30 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesorder_api', '0004_salesorder_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
